grails-app/domain/br/com/petrobras/paap/ProcessStatus.groovy
package br.com.petrobras.paap
import java.text.SimpleDateFormat
class ProcessStatus {

	long startTime
	long endTime
	String type
	String status
	String msg
    long elapsedTime

    static SimpleDateFormat formatter = new SimpleDateFormat('dd-MM-yyyy HH:mm:ss', new Locale("pt", "BR"))

    static constraints = {
    	startTime nullable: false
    	endTime nullable: true
    	type nullable: false
    	status nullable: false
    	msg nullable:true
    }
    static mapping = {
        sort startTime:"desc"
        msg type: "text"
        elapsedTime formula: "END_TIME - START_TIME"
    }

    String getFormattedStartTime(){
        return formatter.format(new Date(startTime))
    }

    String getFormattedEndTime(){
        return formatter.format(new Date(endTime))
    }

    String getFormattedDuration(){
        return (endTime ? endTime :  new Date().getTime()) - startTime + "ms" 
    }
}

grails-app/controllers/br/com/petrobras/paap/ProcessStatusController.groovy
package br.com.petrobras.paap

import br.com.petrobras.paap.timeseries.TimeSeriesDownsampler
import grails.converters.JSON
import groovy.time.TimeCategory

class ProcessStatusController {

    static namespace = 'admin'
    private final static PAGE_SIZE_HOURS = 6

    def index() {
    	params.max = 50
        def meanTimePerType = ProcessStatus.createCriteria().list {
            ne 'endTime', 0L
            projections{
                groupProperty("type")
                avg('elapsedTime')
            }
        }.collectEntries {
            [it[0], it[1]]  // [type, value]
        }

        def result, count
        if (params.type) {
            result = ProcessStatus.findAllByType(params.type, params)
            count = ProcessStatus.countByType(params.type)
        } else {
            result = ProcessStatus.list(params)
            count = ProcessStatus.count()
        }

        respond result, model:[processStatusInstanceCount: count, meanTimePerType: meanTimePerType]
    }

    def chart() {
        respond view:'processStatus/graph.gsp', model:[page: 1]
    }

    def allStatus() {
        def result = [:] as TreeMap
        Date fromDate, toDate, now = new Date()
        def page = params.page ? Integer.valueOf(params.page) : 1
        use (TimeCategory) {
            fromDate = now - (page*PAGE_SIZE_HOURS).hour
            toDate = fromDate + (PAGE_SIZE_HOURS).hour
        }

        ProcessStatus.findAllByStartTimeBetween(fromDate.time, toDate.time, [sort: 'startTime', order: 'asc']).each { ProcessStatus status ->
            def type = status.type.substring(status.type.lastIndexOf('.')+1)
            def listForType = result[type]
            if (!listForType) {
                result[type] = listForType = [] as LinkedList
            }

            if (status.endTime > status.startTime) {
                listForType << ([status.endTime, status.elapsedTime] as Number[])
            }
        }

        result = result.collectEntries { String key, List<Number[]> values ->
            [key, TimeSeriesDownsampler.largestTriangleThreeBucketsTimeArray(values, 1000) ]
        }

        render result as JSON
    }
}

grails-app/views/processStatus/chart.gsp
<%@ page import="br.com.petrobras.paap.ProcessStatus" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'processStatus.label', default: 'ProcessStatus')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body class="admin">

		<nav class="navbar navbar-default">
			<div class="container-fluid" role="navigation">
				<ul class="nav navbar-nav">
					<li><g:link class="list" action="index" namespace="admin"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
					<li><g:link class="chart" action="chart" namespace="admin"><g:message code="processStatus.chart.label" /></g:link></li>
				</ul>
			</div>
		</nav>
		<div class="admin-title">
			<h2><g:message code="processStatus.chart.label" args="[entityName]" /></h2>
		</div>
		<div id="list-processStatus" class="content scaffold-list" role="main">
			<div class="">
				<div id="chart"></div>
				<button name="older" id="btn-older" class="btn">Older</button>
				<button name="newer" id="btn-newer" class="btn">Newer</button>
			</div>
		</div>

		<g:javascript>
			var chart = null ;
			var currPage = 1 ;

			var nextColor = 0 ;
			var colors = ["#DDDF0D", "#55BF3B", "#DF5353", "#7798BF", "#aaeeee", "#ff0066", "#eeaaee",
				"#55BF3B", "#DF5353", "#7798BF", "#aaeeee"] ;
			var colorByType = {} ;

			function getPage(page) {
				if(page > 0) {
					currPage = page ;
					chart.showLoading() ;
					$.getJSON( "${createLink(action: 'allStatus', namespace: 'admin')}", {page: page}, function( data ) {
						// Remove series
						while(chart.series.length > 0) chart.series[0].remove(true);

						// Add new series
						for(var type in data) {
							var values = data[type] ;

							var color = colorByType[type] ;
							if(!color){
								color = colors[nextColor++] ;
								colorByType[type] = color ;
							}

							chart.addSeries({
								name:type,
								data: values,
								color:color
							} );
						}

						chart.hideLoading() ;
						chart.redraw() ;
					}) ;
				}
			}

			$("#btn-older").click(function(){
				getPage(currPage+1);
			});
			$("#btn-newer").click(function(){
				getPage(currPage-1);
			});


			$(document).ready(function() {
				Highcharts.setOptions({
					global: {
						useUTC: false
					}
				});

				var options = {
					chart: {
						renderTo: 'chart',
						zoomType: 'xy',
						height: 600
					},
					legend: {
						enabled: true,
						layout: 'vertical',
						align: 'right',
						verticalAlign: 'middle'
					},
					credits: false,
					title: {
						text: 'Process Status'
					},
					yAxis: {
						title: {
							text: 'Duração (ms)'
						},
						gridLineWidth: 1,
						min: 0
					},
					xAxis: {
						type: 'datetime',
						gridLineWidth: 1,
						title: {
							text: null
						}
					},
					series: [{
						data: [],
						allowPointSelect: true,
						lineWidth: 1,
						id: 'primary'
					}]
				} ;

				chart = new Highcharts.Chart(options);

				getPage(1) ;
			});

		</g:javascript>
	</body>
</html>

grails-app/views/processStatus/index.gsp
<%@ page import="br.com.petrobras.paap.ProcessStatus" %>
<!DOCTYPE html>
<html xmlns:g="http://www.w3.org/1999/html">
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'processStatus.label', default: 'ProcessStatus')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body class="admin">

		<nav class="navbar navbar-default">
			<div class="container-fluid" role="navigation">
				<ul class="nav navbar-nav">
					<li><g:link class="list" action="index" namespace="admin"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
					<li><g:link class="chart" action="chart" namespace="admin"><g:message code="processStatus.chart.label" /></g:link></li>
				</ul>
			</div>
		</nav>
		<div class="admin-title">
			<h2><g:message code="default.list.label" args="[entityName]" /></h2>
		</div>

		<div id="list-processStatus" class="content scaffold-list" role="main">
			<div class="container">
			<div id="list-tagPI" class="col-md-12" role="main">

				<!-- Average of times -->
				<a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapse-avg-times" aria-expanded="false" aria-controls="collapse-avg-times">
					Show average time by type
				</a>
				<div class="collapse" id="collapse-avg-times">
					<h3>Average time by type</h3>
					<table class="table">
						<tr>
							<th>Class</th>
							<th>Average Time</th>
						</tr>
						<g:each in="${meanTimePerType.sort{-it.value}}" var="meanTime">
							<tr>
								<td>
									<g:link class="list" action="index" namespace="admin" params="${[type: meanTime.key]}">
										${meanTime.key.substring(meanTime.key.lastIndexOf('.')+1)}
									</g:link>
								</td>
								<td style="text-align: right">
									<g:formatNumber number="${meanTime.value}" format="#,###.0" /> ms
								</td>
							</tr>
						</g:each>
					</table>
				</div>

			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>

			<!-- Content -->
			<table class="table">
			<thead>
					<tr>
					
						<g:sortableColumn property="startTime" title="${message(code: 'processStatus.startTime.label', default: 'Start Time')}" />
						<g:sortableColumn property="endTime" title="${message(code: 'processStatus.endTime.label', default: 'End Time')}" />
						<g:sortableColumn property="elapsedTime" title="${message(code: 'processStatus.elapsedTime.label', default: 'Duration')}" />
						<th>% of average</th>
						<g:sortableColumn property="type" title="${message(code: 'processStatus.type.label', default: 'Type')}" />
						<g:sortableColumn property="status" title="${message(code: 'processStatus.status.label', default: 'Status')}" />
						<g:sortableColumn property="msg" title="${message(code: 'processStatus.msg.label', default: 'Msg')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${processStatusInstanceList}" status="i" var="processStatusInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>${fieldValue(bean: processStatusInstance, field: "formattedStartTime")}</td>
						<td>
							<g:if test="${processStatusInstance.endTime > 0}">
								${fieldValue(bean: processStatusInstance, field: "formattedEndTime")}
							</g:if>
							<g:else>
								N/A
							</g:else>
						</td>
						<td style="text-align: right">
						<g:if test="${processStatusInstance.endTime > 0}">
							${fieldValue(bean: processStatusInstance, field: "elapsedTime")}ms
							<g:set var="percentOfMean" value="${processStatusInstance.elapsedTime * 100 / meanTimePerType[processStatusInstance.type]}" />
							<g:if test="${percentOfMean < 50}">
								<g:set var="valueColor" value="#76FFFF" />
							</g:if>
							<g:elseif test="${percentOfMean < 120}">
								<g:set var="valueColor" value="#AEFAAE" />
							</g:elseif>
							<g:elseif test="${percentOfMean < 180}">
								<g:set var="valueColor" value="#FFFF93" />
							</g:elseif>
							<g:else>
								<g:set var="valueColor" value="#FF8A8A" />
							</g:else>
						</g:if>
						<g:else>
							${fieldValue(bean: processStatusInstance, field: "formattedDuration")}
						</g:else>
						</td>
						<td style="background-color: ${valueColor}; text-align: right">
							<g:if test="${percentOfMean}">
								<g:formatNumber number="${percentOfMean}" format="#" />%
							</g:if>
							<g:else>
								N/A
							</g:else>
						</td>
						<td>
							<g:if test="${params.type}">
								${processStatusInstance.type.substring(processStatusInstance.type.lastIndexOf('.')+1)}
							</g:if>
							<g:else>
								<g:link class="list" action="index" namespace="admin" params="${[type: processStatusInstance.type]}">
									${processStatusInstance.type.substring(processStatusInstance.type.lastIndexOf('.')+1)}
								</g:link>
							</g:else>
						</td>
						<td>${fieldValue(bean: processStatusInstance, field: "status")}</td>
						<td>${fieldValue(bean: processStatusInstance, field: "msg")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${processStatusInstanceCount ?: 0}" namespace="admin" params="${[type: params.type]}" />
			</div>
		</div>
		</div>
	</body>
</html>

grails-app/views/processStatus/show.gsp
<%@ page import="br.com.petrobras.paap.ProcessStatus" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'processStatus.label', default: 'ProcessStatus')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-processStatus" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><g:link class="list" action="index" namespace="admin"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create" namespace="admin"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-processStatus" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list processStatus">
			
				<g:if test="${processStatusInstance?.startTime}">
				<li class="fieldcontain">
					<span id="startTime-label" class="property-label"><g:message code="processStatus.startTime.label" default="Start Time" /></span>
					
						<span class="property-value" aria-labelledby="startTime-label"><g:fieldValue bean="${processStatusInstance}" field="startTime"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${processStatusInstance?.endTime}">
				<li class="fieldcontain">
					<span id="endTime-label" class="property-label"><g:message code="processStatus.endTime.label" default="End Time" /></span>
					
						<span class="property-value" aria-labelledby="endTime-label"><g:fieldValue bean="${processStatusInstance}" field="endTime"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${processStatusInstance?.type}">
				<li class="fieldcontain">
					<span id="type-label" class="property-label"><g:message code="processStatus.type.label" default="Type" /></span>
					
						<span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${processStatusInstance}" field="type"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${processStatusInstance?.status}">
				<li class="fieldcontain">
					<span id="status-label" class="property-label"><g:message code="processStatus.status.label" default="Status" /></span>
					
						<span class="property-value" aria-labelledby="status-label"><g:fieldValue bean="${processStatusInstance}" field="status"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${processStatusInstance?.msg}">
				<li class="fieldcontain">
					<span id="msg-label" class="property-label"><g:message code="processStatus.msg.label" default="Msg" /></span>
					
						<span class="property-value" aria-labelledby="msg-label"><g:fieldValue bean="${processStatusInstance}" field="msg"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:processStatusInstance, action:'delete', namespace: 'admin']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${processStatusInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>